# Generated by Django 5.2.16 on 2026-08-06 13:33
# ruff: noqa: E501, RUF012

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_job_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('country', models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('workplace_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], db_index=True, default=None, max_length=16, null=True)),
                ('employment_type', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('seniority_level', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('job_function', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('source_job_url', models.URLField(blank=True, default=None, max_length=2048, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('not_found', 'Nicht mehr gefunden'), ('closed', 'Geschlossen')], db_index=True, default='active', max_length=16)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedupe_key', models.CharField(max_length=64)),
                ('consecutive_successful_misses', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'status'], name='job_company_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'source', 'dedupe_key'), name='uniq_job_dedupe_key'), models.UniqueConstraint(condition=models.Q(('source_job_id__isnull', False), models.Q(('source_job_id', ''), _negated=True)), fields=('company', 'source', 'source_job_id'), name='uniq_job_source_id'), models.CheckConstraint(condition=models.Q(models.Q(('source_job_id__isnull', False), models.Q(('source_job_id', ''), _negated=True)), models.Q(('source_job_url__isnull', False), models.Q(('source_job_url', ''), _negated=True)), _connector='OR'), name='job_has_source_identity')],
            },
        ),
    ]
