# Generated by Django 5.2.16 on 2026-08-11 15:55
# ruff: noqa: E501, RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysource'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='companies.companysource'),
        ),
    ]
