# Generated by Django 5.2.16 on 2026-08-11 16:10
# ruff: noqa: E501, RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_backfill_company_sources'),
        ('jobs', '0002_jobposting_company_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobposting',
            name='uniq_job_dedupe_key',
        ),
        migrations.RemoveConstraint(
            model_name='jobposting',
            name='uniq_job_source_id',
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('company_source__isnull', True)), fields=('company', 'source', 'dedupe_key'), name='uniq_job_dedupe_key'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('company_source__isnull', True), ('source_job_id__isnull', False), models.Q(('source_job_id', ''), _negated=True)), fields=('company', 'source', 'source_job_id'), name='uniq_job_source_id'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('company_source__isnull', False)), fields=('company_source', 'dedupe_key'), name='uniq_source_job_dedupe_key'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('company_source__isnull', False), ('source_job_id__isnull', False), models.Q(('source_job_id', ''), _negated=True)), fields=('company_source', 'source_job_id'), name='uniq_source_job_source_id'),
        ),
    ]
