# Generated by Django 5.2.16 on 2026-08-06 13:33
# ruff: noqa: E501, RUF012

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('jobs_found', models.PositiveIntegerField(default=0)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('requests_made', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrape_runs', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', '-started_at'], name='run_company_started_idx'), models.Index(fields=['status', '-started_at'], name='run_status_started_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('company',), name='uniq_running_run_company'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'running'), ('finished_at__isnull', True), ('duration_seconds__isnull', True)), models.Q(models.Q(('status', 'running'), _negated=True), ('finished_at__isnull', False), ('duration_seconds__isnull', False)), _connector='OR'), name='run_terminal_fields_valid')],
            },
        ),
    ]
