# Generated by Django 5.2.16 on 2026-08-11 16:36
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_backfill_company_sources"),
        ("scrape_runs", "0002_scraperun_company_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scraperun",
            name="uniq_running_run_company",
        ),
        migrations.AddConstraint(
            model_name="scraperun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_source__isnull", True), ("status", "running")),
                fields=("company",),
                name="uniq_running_run_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="scraperun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_source__isnull", False), ("status", "running")),
                fields=("company_source",),
                name="uniq_running_run_source",
            ),
        ),
    ]
