# Generated by Django 5.2.16 on 2026-08-20
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_backfill_company_sources"),
        ("scrape_runs", "0003_remove_scraperun_uniq_running_run_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scraperun",
            name="company_source",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrape_runs",
                to="companies.companysource",
            ),
        ),
    ]
