# Generated by Django 5.2.16 on 2026-08-06 13:33
# ruff: noqa: E501, RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('source_jobs_url', models.URLField(blank=True, default=None, max_length=2048, null=True)),
                ('company_type', models.CharField(choices=[('client', 'Kunde'), ('supplier', 'Supplier'), ('other', 'Sonstige')], default='other', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_scrape_status', models.CharField(choices=[('never', 'Never'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='never', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'company_type'], name='company_active_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_jobs_url__isnull', False), models.Q(('source_jobs_url', ''), _negated=True)), fields=('source', 'source_jobs_url'), name='uniq_company_source_url')],
            },
        ),
    ]
