# Generated by Django 5.2.16 on 2026-08-11 15:55
# ruff: noqa: E501, RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('source_jobs_url', models.URLField(blank=True, default=None, max_length=2048, null=True)),
                ('approval_status', models.CharField(choices=[('discovered', 'Discovered'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('rejected', 'Rejected')], db_index=True, default='discovered', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'source', 'source_jobs_url'), name='uniq_company_source_config'), models.UniqueConstraint(condition=models.Q(('source_jobs_url__isnull', True)), fields=('company', 'source'), name='uniq_company_source_no_url'), models.CheckConstraint(condition=models.Q(('is_active', False), ('approval_status', 'approved'), _connector='OR'), name='active_source_is_approved'), models.CheckConstraint(condition=models.Q(models.Q(('approval_status', 'approved'), _negated=True), models.Q(('source', ''), _negated=True), _connector='OR'), name='approved_source_has_key')],
            },
        ),
    ]
