"""Source-neutral adapter contracts and the local fixture implementation."""

from scraping.sources.base import (
    SourceAdapter,
    SourceBatch,
    SourceCompany,
    SourceError,
    SourceRecord,
)
from scraping.sources.fixture import (
    FixtureFileNotFoundError,
    FixtureFormatError,
    FixtureRecord,
    FixtureSourceAdapter,
    FixtureSourceError,
    load_fixture_records,
)
from scraping.sources.generic import (
    CandidateValidationError,
    ExtractedJob,
    FakeJobExtractionProvider,
    GenericCandidate,
    GenericCandidateExtractorError,
    GenericExtractionError,
    GenericSourceAdapter,
    JobExtractionProvider,
    JobExtractionResult,
    OpenAIJobExtractionProvider,
    ProviderConfigurationError,
    ProviderResponseError,
    candidate_id_for_url,
    extract_generic_candidates,
    extract_jobs_from_html,
    validate_extracted_jobs,
)

__all__ = [
    "CandidateValidationError",
    "ExtractedJob",
    "FakeJobExtractionProvider",
    "FixtureFileNotFoundError",
    "FixtureFormatError",
    "FixtureRecord",
    "FixtureSourceAdapter",
    "FixtureSourceError",
    "GenericCandidate",
    "GenericCandidateExtractorError",
    "GenericExtractionError",
    "GenericSourceAdapter",
    "JobExtractionProvider",
    "JobExtractionResult",
    "OpenAIJobExtractionProvider",
    "ProviderConfigurationError",
    "ProviderResponseError",
    "SourceAdapter",
    "SourceBatch",
    "SourceCompany",
    "SourceError",
    "SourceRecord",
    "candidate_id_for_url",
    "extract_generic_candidates",
    "extract_jobs_from_html",
    "load_fixture_records",
    "validate_extracted_jobs",
]
