# Generated by Django 5.2.16 on 2026-08-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [  # noqa: RUF012
        ("companies", "0003_backfill_company_sources"),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="DiscoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("supplied_domain", models.CharField(blank=True, default="", max_length=253)),
                ("official_website_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("careers_url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("connected", "Connected"),
                            ("already_connected", "Already connected"),
                            ("needs_review", "Needs review"),
                            ("unsupported", "Unsupported"),
                            ("not_found", "Not found"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_runs",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveryCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official_site", "Official site"),
                            ("careers", "Careers page"),
                            ("source", "Vacancy source"),
                        ],
                        max_length=16,
                    ),
                ),
                ("discovered_url", models.URLField(max_length=2048)),
                ("canonical_url", models.URLField(max_length=2048)),
                ("platform", models.CharField(blank=True, default="", max_length=80)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("evidence", models.JSONField(default=list)),
                ("redirects", models.JSONField(default=list)),
                ("supported", models.BooleanField(default=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("connected", "Connected"),
                            ("already_connected", "Already connected"),
                            ("needs_review", "Needs review"),
                            ("unsupported", "Unsupported"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.companysource",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="discovery.discoveryrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="discoveryrun",
            index=models.Index(
                fields=["company", "-started_at"], name="discovery_company_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="discoverycandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 100)),
                name="discovery_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoverycandidate",
            constraint=models.UniqueConstraint(
                fields=("run", "kind", "canonical_url"), name="uniq_discovery_candidate"
            ),
        ),
    ]
