# Generated by Django 5.2 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("companies", "0003_backfill_company_sources"),
        ("discovery", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="discoverycandidate",
            name="origin",
            field=models.CharField(
                choices=[
                    ("existing_source", "Existing source"),
                    ("current_discovery", "Found in current discovery"),
                    ("previous_discovery", "Found in previous discovery"),
                    ("adapter_search", "Found by adapter-specific search"),
                ],
                default="current_discovery",
                max_length=24,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="discoverycandidate",
            name="uniq_discovery_candidate",
        ),
        migrations.CreateModel(
            name="DiscoveryAdapterCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("found", "Found"),
                            ("already_connected", "Already connected"),
                            ("not_found", "Not found"),
                            ("not_checked", "Not checked"),
                            ("search_failed", "Search failed"),
                            ("validation_failed", "Validation failed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adapter_checks",
                        to="discovery.discoverycandidate",
                    ),
                ),
                (
                    "company_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_adapter_checks",
                        to="companies.companysource",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adapter_checks",
                        to="discovery.discoveryrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="discoverycandidate",
            constraint=models.UniqueConstraint(
                fields=("run", "kind", "platform", "canonical_url"),
                name="uniq_discovery_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryadaptercheck",
            constraint=models.UniqueConstraint(
                fields=("run", "platform"),
                name="uniq_discovery_adapter_check",
            ),
        ),
    ]
