# Generated by Django 5.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("discovery", "0002_discovery_inventory")]  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="discoverycandidate",
            name="is_ignored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discoverycandidate",
            name="job_source_confidence",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discoverycandidate",
            name="job_source_eligibility",
            field=models.CharField(
                choices=[
                    ("supported_ats", "Supported ATS"),
                    ("unsupported_ats", "Unsupported ATS"),
                    ("external_job_board", "External job board"),
                    ("company_jobs_page", "Company jobs page"),
                    ("possible_job_source", "Possible job source"),
                    ("not_a_job_source", "Not a job source"),
                    ("uncertain", "Uncertain"),
                ],
                default="uncertain",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="discoverycandidate",
            name="official_site_eligibility",
            field=models.CharField(
                choices=[
                    ("official_site", "Official site"),
                    ("not_official_site", "Not an official site"),
                    ("uncertain", "Uncertain"),
                ],
                default="uncertain",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="discoverycandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("job_source_confidence__gte", 0),
                    ("job_source_confidence__lte", 100),
                ),
                name="discovery_job_source_confidence_range",
            ),
        ),
    ]
